// <auto-generated />
using BlazorWebAssemblyProjectTest.Server.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorWebAssemblyProjectTest.Server.Migrations
{
    [DbContext(typeof(SqlServerDbContext))]
    partial class SqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorWebAssemblyProjectTest.Shared.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SelfTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelfTypeId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Answer 1",
                            QuestionId = 1,
                            SelfTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Answer 2",
                            QuestionId = 1,
                            SelfTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Answer 3",
                            QuestionId = 1,
                            SelfTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Answer 4",
                            QuestionId = 2,
                            SelfTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Answer 5",
                            QuestionId = 2,
                            SelfTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Answer 6",
                            QuestionId = 2,
                            SelfTypeId = 3
                        });
                });

            modelBuilder.Entity("BlazorWebAssemblyProjectTest.Shared.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Question 1",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Question 2",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Question 3",
                            Type = 3
                        });
                });

            modelBuilder.Entity("BlazorWebAssemblyProjectTest.Shared.SelfType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SelfTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SelfType 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SelfType 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SelfType 3"
                        });
                });

            modelBuilder.Entity("BlazorWebAssemblyProjectTest.Shared.Answer", b =>
                {
                    b.HasOne("BlazorWebAssemblyProjectTest.Shared.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorWebAssemblyProjectTest.Shared.SelfType", "SelfType")
                        .WithMany()
                        .HasForeignKey("SelfTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("SelfType");
                });
#pragma warning restore 612, 618
        }
    }
}
